export const companyDatasets = [
  {
    id: "COMP-2023-78901",
    legalName: "Synapse Robotics Corporation",
    stateOfIncorporation: "Michigan",
    industry: "Robotics & Automation",
    totalNumberOfEmployees: 127,
    numberOfFullTimeEmployees: 112,
    numberOfPartTimeEmployees: 15,
    website: "https://synapserobotics.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/synapserobotics",
    facebookCompanyPage: "https://facebook.com/synapserobotics",
    otherInformation:
      "Founded in 2018, Synapse Robotics develops industrial automation solutions for manufacturing and warehouse operations. Their flagship robotic system has been adopted by automotive and electronics manufacturers across the Midwest and Canada.",
    fax: "+1 (248) 555-9876",
    phone: "(248) 555-1234",
    email: "info@synapserobotics.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Michigan",
      city: "Detroit",
      street: "1500 Woodward Avenue, Suite 400",
      zipCode: "48226",
    },
    mailingAddress: {
      country: "United States",
      state: "Michigan",
      city: "Ann Arbor",
      street: "2355 Bonisteel Boulevard",
      zipCode: "48109",
    },
    primaryContactPerson: {
      firstName: "Marcus",
      lastName: "Rodriguez",
      phone: "(248) 555-5678",
      email: "m.rodriguez@synapserobotics.example.com",
    },
  },
  {
    id: "COMP-2024-13579",
    legalName: "Aqua Purification Systems LLC",
    stateOfIncorporation: "Arizona",
    industry: "Water Technology",
    totalNumberOfEmployees: 93,
    numberOfFullTimeEmployees: 85,
    numberOfPartTimeEmployees: 8,
    website: "https://aquapurification.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/aquapurificationsystems",
    facebookCompanyPage: "https://facebook.com/aquapurificationsystems",
    otherInformation:
      "Established in 2016, specializing in water purification and conservation technologies for arid regions. Their systems are installed in over 200 communities across the Southwest United States and have expanded to similar climate regions in the Middle East.",
    fax: "+1 (602) 555-6789",
    phone: "(602) 555-2345",
    email: "contact@aquapurification.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Arizona",
      city: "Phoenix",
      street: "2700 N Central Avenue, Suite 800",
      zipCode: "85004",
    },
    mailingAddress: {
      country: "United States",
      state: "Arizona",
      city: "Phoenix",
      street: "2700 N Central Avenue, Suite 800",
      zipCode: "85004",
    },
    primaryContactPerson: {
      firstName: "Elena",
      lastName: "Sanchez",
      phone: "(602) 555-8765",
      email: "e.sanchez@aquapurification.example.com",
    },
  },
  {
    id: "COMP-2022-24680",
    legalName: "Cirrus Analytics Inc.",
    stateOfIncorporation: "Virginia",
    industry: "Data Analytics",
    totalNumberOfEmployees: 219,
    numberOfFullTimeEmployees: 205,
    numberOfPartTimeEmployees: 14,
    website: "https://cirrusanalytics.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/cirrusanalytics",
    facebookCompanyPage: "https://facebook.com/cirrusanalyticsinc",
    otherInformation:
      "Founded in 2013, Cirrus Analytics specializes in predictive analytics and machine learning solutions for government and defense sectors. The company holds top security clearances and has completed projects for multiple federal agencies.",
    fax: "+1 (703) 555-9876",
    phone: "(703) 555-4321",
    email: "info@cirrusanalytics.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Virginia",
      city: "Arlington",
      street: "1776 Wilson Boulevard, Suite 500",
      zipCode: "22209",
    },
    mailingAddress: {
      country: "United States",
      state: "Virginia",
      city: "Reston",
      street: "12110 Sunset Hills Road, Suite 600",
      zipCode: "20190",
    },
    primaryContactPerson: {
      firstName: "Jonathan",
      lastName: "Walker",
      phone: "(703) 555-7890",
      email: "j.walker@cirrusanalytics.example.com",
    },
  },
  {
    id: "COMP-2023-97531",
    legalName: "Evergreen Materials Group Inc.",
    stateOfIncorporation: "Oregon",
    industry: "Sustainable Manufacturing",
    totalNumberOfEmployees: 154,
    numberOfFullTimeEmployees: 138,
    numberOfPartTimeEmployees: 16,
    website: "https://evergreenmaterials.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/evergreenmaterials",
    facebookCompanyPage: "https://facebook.com/evergreenmaterialsgroup",
    otherInformation:
      "Established in 2015, producing sustainable packaging materials from recycled and biodegradable sources. The company has developed proprietary processes for converting agricultural waste into durable packaging products now used by major retailers nationwide.",
    fax: "+1 (541) 555-6789",
    phone: "(541) 555-3456",
    email: "sales@evergreenmaterials.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Oregon",
      city: "Eugene",
      street: "1850 Millrace Drive",
      zipCode: "97403",
    },
    mailingAddress: {
      country: "United States",
      state: "Oregon",
      city: "Eugene",
      street: "1850 Millrace Drive",
      zipCode: "97403",
    },
    primaryContactPerson: {
      firstName: "Thomas",
      lastName: "Wilson",
      phone: "(541) 555-8765",
      email: "t.wilson@evergreenmaterials.example.com",
    },
  },
  {
    id: "COMP-2024-86420",
    legalName: "Helix Genomics LLC",
    stateOfIncorporation: "Maryland",
    industry: "Medical Diagnostics",
    totalNumberOfEmployees: 73,
    numberOfFullTimeEmployees: 65,
    numberOfPartTimeEmployees: 8,
    website: "https://helixgenomics.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/helixgenomics",
    facebookCompanyPage: "https://facebook.com/helixgenomicsllc",
    otherInformation:
      "Founded in 2020, Helix Genomics develops rapid diagnostic tests for infectious diseases using proprietary DNA sequencing technology. The company has partnerships with several major hospital networks and has received FDA approval for two of its testing platforms.",
    fax: "+1 (410) 555-9876",
    phone: "(410) 555-1234",
    email: "contact@helixgenomics.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Maryland",
      city: "Baltimore",
      street: "701 East Pratt Street, Suite 600",
      zipCode: "21202",
    },
    mailingAddress: {
      country: "United States",
      state: "Maryland",
      city: "Rockville",
      street: "9800 Medical Center Drive",
      zipCode: "20850",
    },
    primaryContactPerson: {
      firstName: "Patricia",
      lastName: "Nguyen",
      phone: "(410) 555-5678",
      email: "p.nguyen@helixgenomics.example.com",
    },
  },
  {
    id: "COMP-2023-05678",
    legalName: "Acme Technologies Inc.",
    stateOfIncorporation: "California",
    industry: "Software Development",
    totalNumberOfEmployees: 150,
    numberOfFullTimeEmployees: 120,
    numberOfPartTimeEmployees: 30,
    website: "https://acmetech.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/acmetech",
    facebookCompanyPage: "https://facebook.com/acmetech",
    otherInformation:
      "Founded in 2015, focused on AI and cloud solutions with a global customer base across North America, Europe, and Asia. The company has received multiple industry awards for innovation.",
    fax: "+1 (555) 123-4567",
    phone: "(555) 987-6543",
    email: "info@acmetech.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "California",
      city: "San Francisco",
      street: "123 Innovation Avenue, Suite 500",
      zipCode: "94105",
    },
    mailingAddress: {
      country: "United States",
      state: "California",
      city: "Palo Alto",
      street: "456 Tech Boulevard, Floor 3",
      zipCode: "94301",
    },
    primaryContactPerson: {
      firstName: "Sarah",
      lastName: "Johnson",
      phone: "(555) 765-4321",
      email: "sarah.johnson@acmetech.example.com",
    },
  },
  {
    id: "COMP-2024-12389",
    legalName: "GreenEnergy Solutions LLC",
    stateOfIncorporation: "Colorado",
    industry: "Renewable Energy",
    totalNumberOfEmployees: 87,
    numberOfFullTimeEmployees: 72,
    numberOfPartTimeEmployees: 15,
    website: "https://greenenergysolutions.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/greenenergysolutions",
    facebookCompanyPage: "https://facebook.com/greenenergysolutions",
    otherInformation:
      "Established in 2018, specializing in solar panel installations and renewable energy consulting. The company has completed over 500 residential and 50 commercial installations across the Western United States.",
    fax: "+1 (303) 555-8765",
    phone: "(303) 555-9876",
    email: "contact@greenenergy.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Colorado",
      city: "Boulder",
      street: "789 Sustainability Way",
      zipCode: "80302",
    },
    mailingAddress: {
      country: "United States",
      state: "Colorado",
      city: "Boulder",
      street: "789 Sustainability Way",
      zipCode: "80302",
    },
    primaryContactPerson: {
      firstName: "Michael",
      lastName: "Chen",
      phone: "(303) 555-4321",
      email: "michael.chen@greenenergy.example.com",
    },
  },
  {
    id: "COMP-2022-34567",
    legalName: "MediNova Health Systems Inc.",
    stateOfIncorporation: "Massachusetts",
    industry: "Healthcare Technology",
    totalNumberOfEmployees: 312,
    numberOfFullTimeEmployees: 287,
    numberOfPartTimeEmployees: 25,
    website: "https://medinova.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/medinova",
    facebookCompanyPage: "https://facebook.com/medinovahealth",
    otherInformation:
      "Founded in 2010, MediNova develops electronic health record systems and telehealth solutions for hospitals and clinics. Their software is currently used in over 200 healthcare facilities across 15 states.",
    fax: "+1 (617) 555-2345",
    phone: "(617) 555-3456",
    email: "info@medinova.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Massachusetts",
      city: "Cambridge",
      street: "50 Innovation Drive, 4th Floor",
      zipCode: "02142",
    },
    mailingAddress: {
      country: "United States",
      state: "Massachusetts",
      city: "Boston",
      street: "100 Medical Plaza, Suite 300",
      zipCode: "02116",
    },
    primaryContactPerson: {
      firstName: "Jennifer",
      lastName: "Patel",
      phone: "(617) 555-7890",
      email: "jennifer.patel@medinova.example.com",
    },
  },
  {
    id: "COMP-2023-98765",
    legalName: "Global Logistics Partners Corp.",
    stateOfIncorporation: "Texas",
    industry: "Transportation & Logistics",
    totalNumberOfEmployees: 523,
    numberOfFullTimeEmployees: 489,
    numberOfPartTimeEmployees: 34,
    website: "https://globallogistics.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/globallogistics",
    facebookCompanyPage: "https://facebook.com/globallogistics",
    otherInformation:
      "Established in 2008, the company operates a fleet of 175 trucks and maintains 12 distribution centers across the Southern United States and Mexico. Specializes in cross-border shipping and cold chain logistics.",
    fax: "+1 (214) 555-6789",
    phone: "(214) 555-1234",
    email: "operations@globallogistics.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Texas",
      city: "Dallas",
      street: "8700 Freight Avenue",
      zipCode: "75247",
    },
    mailingAddress: {
      country: "United States",
      state: "Texas",
      city: "Dallas",
      street: "8700 Freight Avenue",
      zipCode: "75247",
    },
    primaryContactPerson: {
      firstName: "Robert",
      lastName: "Garcia",
      phone: "(214) 555-5678",
      email: "r.garcia@globallogistics.example.com",
    },
  },
  {
    id: "COMP-2024-45678",
    legalName: "Urban Harvest Farms Inc.",
    stateOfIncorporation: "New York",
    industry: "Agriculture & Food Production",
    totalNumberOfEmployees: 42,
    numberOfFullTimeEmployees: 28,
    numberOfPartTimeEmployees: 14,
    website: "https://urbanharvestfarms.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/urbanharvestfarms",
    facebookCompanyPage: "https://facebook.com/urbanharvestfarms",
    otherInformation:
      "Founded in 2019, Urban Harvest operates vertical farms in repurposed urban buildings. The company supplies fresh produce to local restaurants and grocery stores within a 50-mile radius of each farm location.",
    fax: "+1 (212) 555-9876",
    phone: "(212) 555-3456",
    email: "grow@urbanharvestfarms.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "New York",
      city: "Brooklyn",
      street: "125 Industrial Way, Building 7",
      zipCode: "11222",
    },
    mailingAddress: {
      country: "United States",
      state: "New York",
      city: "New York",
      street: "350 Madison Avenue, Suite 1200",
      zipCode: "10017",
    },
    primaryContactPerson: {
      firstName: "Aisha",
      lastName: "Washington",
      phone: "(212) 555-7890",
      email: "aisha.w@urbanharvestfarms.example.com",
    },
  },
  {
    id: "COMP-2022-76543",
    legalName: "Quantum Financial Services Ltd.",
    stateOfIncorporation: "Illinois",
    industry: "Financial Technology",
    totalNumberOfEmployees: 176,
    numberOfFullTimeEmployees: 165,
    numberOfPartTimeEmployees: 11,
    website: "https://quantumfinancial.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/quantumfinancial",
    facebookCompanyPage: "https://facebook.com/quantumfinancialservices",
    otherInformation:
      "Established in 2016, specializing in algorithmic trading platforms and financial analytics for institutional investors. The company manages over $2 billion in assets and serves clients in North America and Europe.",
    fax: "+1 (312) 555-4321",
    phone: "(312) 555-8765",
    email: "info@quantumfinancial.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Illinois",
      city: "Chicago",
      street: "233 South Wacker Drive, 85th Floor",
      zipCode: "60606",
    },
    mailingAddress: {
      country: "United States",
      state: "Illinois",
      city: "Chicago",
      street: "233 South Wacker Drive, 85th Floor",
      zipCode: "60606",
    },
    primaryContactPerson: {
      firstName: "David",
      lastName: "Kim",
      phone: "(312) 555-1234",
      email: "d.kim@quantumfinancial.example.com",
    },
  },
  {
    id: "COMP-2023-23456",
    legalName: "OceanBlue Biotechnology Inc.",
    stateOfIncorporation: "Washington",
    industry: "Biotechnology",
    totalNumberOfEmployees: 89,
    numberOfFullTimeEmployees: 76,
    numberOfPartTimeEmployees: 13,
    website: "https://oceanbluebio.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/oceanbluebio",
    facebookCompanyPage: "https://facebook.com/oceanbluebiotechnology",
    otherInformation:
      "Founded in 2017, focused on developing sustainable pharmaceuticals from marine organisms. The company has three patents pending and collaborates with research institutions across North America and Asia.",
    fax: "+1 (206) 555-9876",
    phone: "(206) 555-3456",
    email: "research@oceanbluebio.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Washington",
      city: "Seattle",
      street: "900 Alaskan Way, Pier 56",
      zipCode: "98104",
    },
    mailingAddress: {
      country: "United States",
      state: "Washington",
      city: "Redmond",
      street: "15800 Research Drive",
      zipCode: "98052",
    },
    primaryContactPerson: {
      firstName: "Emma",
      lastName: "Roberts",
      phone: "(206) 555-7890",
      email: "e.roberts@oceanbluebio.example.com",
    },
  },
  {
    id: "COMP-2024-87654",
    legalName: "NextGen Construction Group LLC",
    stateOfIncorporation: "Florida",
    industry: "Construction",
    totalNumberOfEmployees: 215,
    numberOfFullTimeEmployees: 197,
    numberOfPartTimeEmployees: 18,
    website: "https://nextgenconstruction.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/nextgenconstruction",
    facebookCompanyPage: "https://facebook.com/nextgenconstructiongroup",
    otherInformation:
      "Established in 2011, specializing in sustainable commercial buildings and hurricane-resistant residential structures. The company has completed projects valued at over $500 million throughout Florida and the Gulf Coast.",
    fax: "+1 (305) 555-8765",
    phone: "(305) 555-2345",
    email: "projects@nextgenconstruction.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Florida",
      city: "Miami",
      street: "2500 Biscayne Boulevard, Suite 800",
      zipCode: "33137",
    },
    mailingAddress: {
      country: "United States",
      state: "Florida",
      city: "Miami",
      street: "2500 Biscayne Boulevard, Suite 800",
      zipCode: "33137",
    },
    primaryContactPerson: {
      firstName: "Carlos",
      lastName: "Mendez",
      phone: "(305) 555-6789",
      email: "c.mendez@nextgenconstruction.example.com",
    },
  },
  {
    id: "COMP-2022-54321",
    legalName: "Frontier AR Technologies Inc.",
    stateOfIncorporation: "Oregon",
    industry: "Augmented Reality",
    totalNumberOfEmployees: 64,
    numberOfFullTimeEmployees: 58,
    numberOfPartTimeEmployees: 6,
    website: "https://frontierAR.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/frontierARtech",
    facebookCompanyPage: "https://facebook.com/frontierARtechnologies",
    otherInformation:
      "Founded in 2019, developing industrial augmented reality solutions for manufacturing, maintenance, and training applications. Their software is used by Fortune 500 companies across aerospace, automotive, and healthcare sectors.",
    fax: "+1 (503) 555-4321",
    phone: "(503) 555-6789",
    email: "solutions@frontierAR.example.com",
    isMailingAddressDifferentFromRegisteredAddress: true,
    registeredAddress: {
      country: "United States",
      state: "Oregon",
      city: "Portland",
      street: "350 Technology Park Drive",
      zipCode: "97204",
    },
    mailingAddress: {
      country: "United States",
      state: "Oregon",
      city: "Beaverton",
      street: "12500 NW Cornell Road, Suite 230",
      zipCode: "97006",
    },
    primaryContactPerson: {
      firstName: "Natalie",
      lastName: "Torres",
      phone: "(503) 555-1234",
      email: "n.torres@frontierAR.example.com",
    },
  },
  {
    id: "COMP-2023-65432",
    legalName: "Meridian Hospitality Group Inc.",
    stateOfIncorporation: "Nevada",
    industry: "Hospitality & Tourism",
    totalNumberOfEmployees: 378,
    numberOfFullTimeEmployees: 297,
    numberOfPartTimeEmployees: 81,
    website: "https://meridianhospitality.example.com",
    linkedInCompanyPage: "https://linkedin.com/company/meridianhospitality",
    facebookCompanyPage: "https://facebook.com/meridianhospitalitygroup",
    otherInformation:
      "Established in 2014, operating a chain of boutique hotels and resorts across the Western United States. The company emphasizes sustainable tourism practices and local cultural experiences with properties in 5 states.",
    fax: "+1 (702) 555-8765",
    phone: "(702) 555-3456",
    email: "reservations@meridianhospitality.example.com",
    isMailingAddressDifferentFromRegisteredAddress: false,
    registeredAddress: {
      country: "United States",
      state: "Nevada",
      city: "Las Vegas",
      street: "3570 Las Vegas Boulevard South",
      zipCode: "89109",
    },
    mailingAddress: {
      country: "United States",
      state: "Nevada",
      city: "Las Vegas",
      street: "3570 Las Vegas Boulevard South",
      zipCode: "89109",
    },
    primaryContactPerson: {
      firstName: "Alexandra",
      lastName: "Blackwell",
      phone: "(702) 555-7890",
      email: "a.blackwell@meridianhospitality.example.com",
    },
  }
]

export default companyDatasets;